apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app.kubernetes.io/name: gateway
    app.kubernetes.io/part-of: bakta-web
    app.kubernetes.io/version: v0.1.0
  name: baktawebgateway
  namespace: bakta-dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: gateway
      app.kubernetes.io/part-of: bakta-web
      app.kubernetes.io/version: v0.1.0
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: gateway
        app.kubernetes.io/part-of: bakta-web
        app.kubernetes.io/version: v0.1.0
    spec:
      containers:
      - env:
        - name: GRPC_GO_LOG_SEVERITY_LEVEL
          value: debug
        - name: GRPC_GO_LOG_VERBOSITY_LEVEL
          value: "2"
        image: harbor.computational.bio.uni-giessen.de/bakta/bakta-web-gateway:0.1.0-beta.1
        name: baktagateway
        ports:
        - containerPort: 9000
          name: 9000tcp2
          protocol: TCP
